ALTER TABLE cohida.orders
    ADD COLUMN issued_coupon_id BIGINT REFERENCES cohida.coupons (id),
    ADD COLUMN coupon_value_cents BIGINT NOT NULL DEFAULT 0;

CREATE TABLE cohida.order_payments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
    deleted_at        TIMESTAMP,
    order_id          BIGINT    NOT NULL REFERENCES cohida.orders (id) ON DELETE CASCADE,
    payment_card_id   BIGINT    NOT NULL REFERENCES cohida.payment_cards (id),
    amount_cents      BIGINT    NOT NULL,
    payment_position  INTEGER   NOT NULL,
    CONSTRAINT ck_order_payments_amount CHECK (amount_cents >= 0),
    CONSTRAINT uk_order_payments_position UNIQUE (order_id, payment_position),
    CONSTRAINT uk_order_payments_card UNIQUE (order_id, payment_card_id)
);
