CREATE TABLE cohida.categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    deleted_at  TIMESTAMP,
    slug        VARCHAR(80) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    CONSTRAINT uk_categories_slug UNIQUE (slug)
);

INSERT INTO cohida.categories (created_at, updated_at, slug, name, description)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'football', 'Futebol', 'Bolas, chuteiras e equipamentos para entrar em campo.'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'running', 'Corrida', 'Tênis, acessórios e itens para superar seu ritmo.'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'training', 'Treino', 'Equipamentos para força, mobilidade e condicionamento.'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'outdoor', 'Outdoor', 'Acessórios para aventura, trilha e exploração.'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'martial-arts', 'Artes marciais', 'Judogis, faixas e acessórios para evoluir no tatame.');
