CREATE SCHEMA IF NOT EXISTS cohida;

CREATE TABLE cohida.customers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    deleted_at TIMESTAMP,
    code       VARCHAR(20)  NOT NULL,
    name       VARCHAR(120) NOT NULL,
    birth_date DATE         NOT NULL,
    cpf        VARCHAR(11)  NOT NULL,
    phone      VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_customers_code UNIQUE (code),
    CONSTRAINT uk_customers_cpf UNIQUE (cpf)
);

CREATE TABLE cohida.admins
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    deleted_at TIMESTAMP,
    name       VARCHAR(120) NOT NULL
);

CREATE TABLE cohida.accounts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    deleted_at    TIMESTAMP,
    customer_id   BIGINT UNIQUE REFERENCES cohida.customers (id),
    admin_id      BIGINT UNIQUE REFERENCES cohida.admins (id),
    email         VARCHAR(254) NOT NULL,
    password_hash VARCHAR(60)  NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_accounts_email UNIQUE (email),
    CONSTRAINT ck_accounts_single_owner CHECK (
        (customer_id IS NOT NULL AND admin_id IS NULL)
            OR (customer_id IS NULL AND admin_id IS NOT NULL)
        )
);

CREATE TABLE cohida.customer_addresses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    deleted_at   TIMESTAMP,
    customer_id  BIGINT       NOT NULL REFERENCES cohida.customers (id),
    label        VARCHAR(80)  NOT NULL,
    type         VARCHAR(20)  NOT NULL,
    street       VARCHAR(160) NOT NULL,
    number       VARCHAR(20)  NOT NULL,
    neighborhood VARCHAR(100) NOT NULL,
    zip_code     VARCHAR(8)   NOT NULL,
    city         VARCHAR(100) NOT NULL,
    state        VARCHAR(2)   NOT NULL,
    country      VARCHAR(80)  NOT NULL
);

CREATE TABLE cohida.audit_logs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP     NOT NULL,
    updated_at       TIMESTAMP     NOT NULL,
    deleted_at       TIMESTAMP,
    actor_account_id VARCHAR(40),
    event_type       VARCHAR(80)   NOT NULL,
    target_type      VARCHAR(80)   NOT NULL,
    target_id        VARCHAR(40)   NOT NULL,
    changed_data     VARCHAR(2000) NOT NULL
);

CREATE INDEX ix_customers_name ON cohida.customers (name);
CREATE INDEX ix_customer_addresses_customer_id ON cohida.customer_addresses (customer_id);
CREATE INDEX ix_audit_logs_target ON cohida.audit_logs (target_type, target_id);
