CREATE TABLE cohida.payment_cards
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    deleted_at      TIMESTAMP,
    customer_id     BIGINT       NOT NULL REFERENCES cohida.customers (id),
    processor_token VARCHAR(255) NOT NULL,
    brand           VARCHAR(40)  NOT NULL,
    last_digits     VARCHAR(4)   NOT NULL,
    label           VARCHAR(120) NOT NULL,
    expiry_month    INTEGER      NOT NULL,
    expiry_year     INTEGER      NOT NULL,
    preferred       BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_payment_cards_processor_token UNIQUE (processor_token),
    CONSTRAINT ck_payment_cards_last_digits CHECK (last_digits ~ '^[0-9]{4}$'),
    CONSTRAINT ck_payment_cards_expiry_month CHECK (expiry_month BETWEEN 1 AND 12)
);

CREATE INDEX ix_payment_cards_customer ON cohida.payment_cards (customer_id);
