CREATE TABLE cohida.products
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP     NOT NULL,
    updated_at    TIMESTAMP     NOT NULL,
    deleted_at    TIMESTAMP,
    code          VARCHAR(24)   NOT NULL,
    slug          VARCHAR(160)  NOT NULL,
    name          VARCHAR(160)  NOT NULL,
    brand         VARCHAR(100)  NOT NULL,
    description   VARCHAR(2000) NOT NULL,
    minimum_stock INTEGER       NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_products_code UNIQUE (code),
    CONSTRAINT uk_products_slug UNIQUE (slug),
    CONSTRAINT ck_products_minimum_stock CHECK (minimum_stock >= 0)
);

CREATE TABLE cohida.product_categories
(
    product_id BIGINT      NOT NULL REFERENCES cohida.products (id) ON DELETE CASCADE,
    category   VARCHAR(80) NOT NULL,
    PRIMARY KEY (product_id, category)
);

CREATE TABLE cohida.product_variants
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    deleted_at     TIMESTAMP,
    product_id     BIGINT       NOT NULL REFERENCES cohida.products (id),
    sku            VARCHAR(80)  NOT NULL,
    label          VARCHAR(120) NOT NULL,
    color          VARCHAR(80),
    size           VARCHAR(40),
    price_cents    BIGINT       NOT NULL,
    stock_quantity INTEGER      NOT NULL,
    CONSTRAINT uk_product_variants_sku UNIQUE (sku),
    CONSTRAINT ck_product_variants_price CHECK (price_cents >= 0),
    CONSTRAINT ck_product_variants_stock CHECK (stock_quantity >= 0)
);

CREATE INDEX ix_products_active_name ON cohida.products (active, name);
CREATE INDEX ix_product_variants_product ON cohida.product_variants (product_id);
