CREATE TABLE cohida.coupons
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                TIMESTAMP    NOT NULL,
    updated_at                TIMESTAMP    NOT NULL,
    deleted_at                TIMESTAMP,
    code                      VARCHAR(50)  NOT NULL,
    description               VARCHAR(500) NOT NULL,
    discount_type             VARCHAR(20)  NOT NULL,
    discount_cents            BIGINT,
    discount_percentage       NUMERIC(5, 2),
    maximum_discount_cents    BIGINT,
    minimum_order_value_cents BIGINT,
    valid_from                TIMESTAMP    NOT NULL,
    expires_at                TIMESTAMP    NOT NULL,
    maximum_uses              INTEGER,
    redeemed_count            INTEGER      NOT NULL DEFAULT 0,
    active                    BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_coupons_code UNIQUE (code),
    CONSTRAINT ck_coupons_discount_type CHECK (discount_type IN ('FIXED_AMOUNT', 'PERCENTAGE')),
    CONSTRAINT ck_coupons_fixed_amount CHECK (
        (discount_type = 'FIXED_AMOUNT' AND discount_cents IS NOT NULL AND discount_cents > 0
            AND discount_percentage IS NULL AND maximum_discount_cents IS NULL)
            OR (discount_type = 'PERCENTAGE' AND discount_cents IS NULL AND discount_percentage > 0
            AND discount_percentage <= 100)
        ),
    CONSTRAINT ck_coupons_max_discount CHECK (maximum_discount_cents IS NULL OR maximum_discount_cents > 0),
    CONSTRAINT ck_coupons_minimum_order CHECK (minimum_order_value_cents IS NULL OR minimum_order_value_cents >= 0),
    CONSTRAINT ck_coupons_validity CHECK (expires_at > valid_from),
    CONSTRAINT ck_coupons_maximum_uses CHECK (maximum_uses IS NULL OR maximum_uses > 0),
    CONSTRAINT ck_coupons_redemptions CHECK (redeemed_count >= 0)
);

CREATE INDEX ix_coupons_active_period ON cohida.coupons (active, valid_from, expires_at);
