CREATE TABLE cohida.carts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    deleted_at  TIMESTAMP,
    customer_id BIGINT    NOT NULL UNIQUE REFERENCES cohida.customers (id),
    coupon_id   BIGINT REFERENCES cohida.coupons (id)
);
CREATE TABLE cohida.cart_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    cart_id    BIGINT    NOT NULL REFERENCES cohida.carts (id) ON DELETE CASCADE,
    variant_id BIGINT    NOT NULL REFERENCES cohida.product_variants (id),
    quantity   INTEGER   NOT NULL,
    CONSTRAINT ck_cart_items_quantity CHECK (quantity > 0),
    CONSTRAINT uk_cart_items_variant UNIQUE (cart_id, variant_id)
);
CREATE TABLE cohida.orders
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL,
    deleted_at            TIMESTAMP,
    customer_id           BIGINT       NOT NULL REFERENCES cohida.customers (id),
    status                VARCHAR(24)  NOT NULL,
    subtotal_cents        BIGINT       NOT NULL,
    discount_cents        BIGINT       NOT NULL,
    shipping_cents        BIGINT       NOT NULL,
    total_cents           BIGINT       NOT NULL,
    coupon_code           VARCHAR(50),
    card_brand            VARCHAR(40)  NOT NULL,
    card_last_digits      VARCHAR(4)   NOT NULL,
    delivery_label        VARCHAR(80)  NOT NULL,
    delivery_street       VARCHAR(160) NOT NULL,
    delivery_number       VARCHAR(20)  NOT NULL,
    delivery_neighborhood VARCHAR(100) NOT NULL,
    delivery_zip_code     VARCHAR(8)   NOT NULL,
    delivery_city         VARCHAR(100) NOT NULL,
    delivery_state        VARCHAR(2)   NOT NULL,
    delivery_country      VARCHAR(80)  NOT NULL,
    CONSTRAINT ck_orders_status CHECK (status IN ('EM_ABERTO', 'EM_PROCESSAMENTO', 'PAGAMENTO_REALIZADO', 'EM_TRANSITO',
                                                  'ENTREGUE')),
    CONSTRAINT ck_orders_amounts CHECK (subtotal_cents >= 0 AND discount_cents >= 0 AND shipping_cents >= 0 AND
                                        total_cents >= 0)
);
CREATE TABLE cohida.order_items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    deleted_at       TIMESTAMP,
    order_id         BIGINT       NOT NULL REFERENCES cohida.orders (id) ON DELETE CASCADE,
    variant_id       BIGINT       NOT NULL,
    product_name     VARCHAR(160) NOT NULL,
    sku              VARCHAR(80)  NOT NULL,
    variant_label    VARCHAR(120) NOT NULL,
    unit_price_cents BIGINT       NOT NULL,
    quantity         INTEGER      NOT NULL,
    CONSTRAINT ck_order_items_values CHECK (unit_price_cents >= 0 AND quantity > 0)
);
CREATE INDEX ix_orders_customer_created ON cohida.orders (customer_id, created_at DESC);
CREATE INDEX ix_orders_status_created ON cohida.orders (status, created_at DESC);
