ALTER TABLE cohida.coupons
    ADD COLUMN origin                 VARCHAR(12) NOT NULL DEFAULT 'ADMIN',
    ADD COLUMN remaining_credit_cents BIGINT,
    ADD COLUMN assigned_customer_id   BIGINT REFERENCES cohida.customers (id);
ALTER TABLE cohida.orders
    ADD COLUMN tracking_code       VARCHAR(100),
    ADD COLUMN cancellation_reason VARCHAR(500);
ALTER TABLE cohida.orders
    DROP CONSTRAINT ck_orders_status;
ALTER TABLE cohida.orders
    ADD CONSTRAINT ck_orders_status CHECK (status IN
                                           ('EM_ABERTO', 'EM_PROCESSAMENTO', 'PAGAMENTO_REALIZADO', 'EM_TRANSITO',
                                            'ENTREGUE', 'CANCELADO'));
CREATE TABLE cohida.return_requests
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP     NOT NULL,
    updated_at       TIMESTAMP     NOT NULL,
    deleted_at       TIMESTAMP,
    order_item_id    BIGINT        NOT NULL UNIQUE REFERENCES cohida.order_items (id),
    status           VARCHAR(20)   NOT NULL,
    reason           VARCHAR(1000) NOT NULL,
    tracking_code    VARCHAR(100),
    issued_coupon_id BIGINT UNIQUE REFERENCES cohida.coupons (id),
    CONSTRAINT ck_return_status CHECK (status IN
                                       ('SOLICITADA', 'ACEITA', 'NEGADA', 'ITEM_ENVIADO', 'ITEM_RECEBIDO', 'PROCESSADA'))
);
