CREATE TABLE cohida.notifications
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    deleted_at  TIMESTAMP,
    customer_id BIGINT       NOT NULL REFERENCES cohida.customers (id),
    type        VARCHAR(60)  NOT NULL,
    message     VARCHAR(240) NOT NULL,
    target_path VARCHAR(240),
    read        BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_notifications_customer_read_created ON cohida.notifications (customer_id, read, created_at DESC);
